name: Build Android App with Ansible

on:
  push:
    branches:
      - main
    paths:
      - 'dgc_android_blank/**'

jobs:
  build-android:
    name: Build Android App via Ansible
    runs-on: self-hosted  # Assuming this is your VM where Ansible and Android SDK are available

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible (if not already installed)
        run: |
          if ! command -v ansible >/dev/null; then
            sudo apt update
            sudo apt install -y ansible
          fi

      - name: Run Ansible Playbook
        run: |
          ansible-playbook dgc_android_blank/ansible/playbook.yml -i "localhost," --connection=local
